#!/usr/bin/env python3
"""
영어 단어장 대량 데이터 생성 - 로컬 기반 고속 버전
- 외부 API 의존 없이 로컬 데이터 기반
- Oxford 5000 + 기본 정의 템플릿 사용
- 번역은 배치로 한번에 처리
"""

import json
import asyncio
import aiohttp
from pathlib import Path
import time

# Oxford 5000 핵심 단어 (레벨별 분류)
# A1: 가장 기초 (500개)
# A2: 기초 (500개) 
# B1: 중급 (1000개)
# B2: 중상급 (1500개)
# C1: 고급 (1500개)

CORE_WORDS = {
    "A1": [
        # 기본 동사
        ("be", "verb", "to exist or live", "I want to be happy."),
        ("have", "verb", "to possess or own", "I have a car."),
        ("do", "verb", "to perform an action", "I do my homework every day."),
        ("say", "verb", "to speak words", "She says hello."),
        ("go", "verb", "to move or travel", "Let's go to the park."),
        ("get", "verb", "to obtain or receive", "I get a gift."),
        ("make", "verb", "to create or produce", "She makes a cake."),
        ("know", "verb", "to be aware of information", "I know the answer."),
        ("think", "verb", "to use the mind", "I think it's good."),
        ("take", "verb", "to grab or receive", "Take this book."),
        ("see", "verb", "to view with eyes", "I see the bird."),
        ("come", "verb", "to move toward", "Please come here."),
        ("want", "verb", "to desire something", "I want ice cream."),
        ("look", "verb", "to direct eyes at", "Look at the sky."),
        ("use", "verb", "to employ for purpose", "Use a pen to write."),
        ("find", "verb", "to discover", "I find my keys."),
        ("give", "verb", "to provide to someone", "Give me the ball."),
        ("tell", "verb", "to communicate information", "Tell me a story."),
        ("work", "verb", "to do a job", "I work at a school."),
        ("call", "verb", "to contact by phone", "Call me later."),
        ("try", "verb", "to attempt", "Try your best."),
        ("ask", "verb", "to request information", "Ask a question."),
        ("need", "verb", "to require", "I need water."),
        ("feel", "verb", "to experience emotion", "I feel happy."),
        ("become", "verb", "to start to be", "She became a doctor."),
        ("leave", "verb", "to go away from", "Leave the room."),
        ("put", "verb", "to place somewhere", "Put it on the table."),
        ("mean", "verb", "to signify", "What does it mean?"),
        ("keep", "verb", "to continue to have", "Keep the change."),
        ("let", "verb", "to allow", "Let me help you."),
        ("begin", "verb", "to start", "Begin the game."),
        ("seem", "verb", "to appear", "You seem tired."),
        ("help", "verb", "to assist", "Help me please."),
        ("show", "verb", "to display", "Show me your work."),
        ("hear", "verb", "to perceive sound", "I hear music."),
        ("play", "verb", "to engage in activity", "Children play outside."),
        ("run", "verb", "to move quickly", "Run fast!"),
        ("move", "verb", "to change position", "Move to the left."),
        ("live", "verb", "to reside", "I live in Seoul."),
        ("believe", "verb", "to accept as true", "I believe you."),
        # 기본 명사
        ("time", "noun", "duration or moment", "What time is it?"),
        ("year", "noun", "365 days period", "This year is great."),
        ("people", "noun", "human beings", "Many people came."),
        ("way", "noun", "method or path", "This is the way."),
        ("day", "noun", "24 hour period", "Have a nice day."),
        ("man", "noun", "adult male", "The man is tall."),
        ("woman", "noun", "adult female", "The woman is kind."),
        ("child", "noun", "young person", "The child is playing."),
        ("world", "noun", "the earth", "Travel the world."),
        ("life", "noun", "existence", "Life is beautiful."),
        ("hand", "noun", "body part", "Raise your hand."),
        ("part", "noun", "portion", "Part of the story."),
        ("place", "noun", "location", "This is a nice place."),
        ("case", "noun", "situation", "In this case."),
        ("week", "noun", "seven days", "See you next week."),
        ("company", "noun", "business", "I work for a company."),
        ("system", "noun", "organized method", "The computer system."),
        ("program", "noun", "plan or software", "Watch a TV program."),
        ("question", "noun", "inquiry", "Ask a question."),
        ("government", "noun", "ruling body", "The government decides."),
        ("number", "noun", "quantity", "Pick a number."),
        ("night", "noun", "dark hours", "Good night!"),
        ("point", "noun", "specific detail", "Good point."),
        ("home", "noun", "residence", "Welcome home."),
        ("water", "noun", "liquid H2O", "Drink water."),
        ("room", "noun", "enclosed space", "Enter the room."),
        ("mother", "noun", "female parent", "I love my mother."),
        ("area", "noun", "region", "This area is safe."),
        ("money", "noun", "currency", "Save money."),
        ("story", "noun", "narrative", "Tell me a story."),
        ("fact", "noun", "truth", "That's a fact."),
        ("month", "noun", "calendar period", "Next month."),
        ("lot", "noun", "large amount", "A lot of people."),
        ("right", "noun", "entitlement", "Human rights."),
        ("study", "noun", "learning", "I study English."),
        ("book", "noun", "written work", "Read a book."),
        ("eye", "noun", "vision organ", "Close your eyes."),
        ("job", "noun", "employment", "Find a job."),
        ("word", "noun", "unit of language", "Learn new words."),
        ("business", "noun", "commercial activity", "Start a business."),
        ("issue", "noun", "topic or problem", "Important issue."),
        ("side", "noun", "edge or aspect", "On this side."),
        ("kind", "noun", "type or sort", "What kind?"),
        ("head", "noun", "top of body", "Use your head."),
        ("house", "noun", "dwelling", "A big house."),
        ("service", "noun", "assistance", "Good service."),
        ("friend", "noun", "companion", "My best friend."),
        ("father", "noun", "male parent", "My father works."),
        ("power", "noun", "strength or control", "Electric power."),
        ("hour", "noun", "60 minutes", "Wait an hour."),
        ("game", "noun", "activity for fun", "Play a game."),
        # 기본 형용사
        ("good", "adjective", "of high quality", "Good job!"),
        ("new", "adjective", "recently made", "A new car."),
        ("first", "adjective", "before all others", "The first time."),
        ("last", "adjective", "final", "The last day."),
        ("long", "adjective", "extended length", "A long road."),
        ("great", "adjective", "excellent", "Great work!"),
        ("little", "adjective", "small", "A little bird."),
        ("own", "adjective", "belonging to oneself", "My own room."),
        ("other", "adjective", "different", "The other way."),
        ("old", "adjective", "not new", "An old book."),
        ("right", "adjective", "correct", "The right answer."),
        ("big", "adjective", "large", "A big dog."),
        ("high", "adjective", "tall", "A high mountain."),
        ("different", "adjective", "not the same", "A different idea."),
        ("small", "adjective", "little", "A small cat."),
        ("large", "adjective", "big", "A large room."),
        ("next", "adjective", "following", "Next week."),
        ("early", "adjective", "before expected time", "Early morning."),
        ("young", "adjective", "not old", "A young girl."),
        ("important", "adjective", "significant", "Important news."),
        ("few", "adjective", "not many", "A few people."),
        ("public", "adjective", "for everyone", "Public park."),
        ("bad", "adjective", "not good", "Bad weather."),
        ("same", "adjective", "identical", "The same color."),
        ("able", "adjective", "capable", "I am able to swim."),
        # 기본 부사
        ("up", "adverb", "toward higher position", "Look up."),
        ("so", "adverb", "to such degree", "So beautiful."),
        ("out", "adverb", "away from inside", "Go out."),
        ("just", "adverb", "exactly", "Just right."),
        ("now", "adverb", "at present", "Do it now."),
        ("how", "adverb", "in what way", "How are you?"),
        ("then", "adverb", "at that time", "And then?"),
        ("more", "adverb", "to greater extent", "More please."),
        ("also", "adverb", "in addition", "I also like it."),
        ("here", "adverb", "in this place", "Come here."),
        ("well", "adverb", "in good manner", "Done well."),
        ("only", "adverb", "solely", "Only you."),
        ("very", "adverb", "extremely", "Very good."),
        ("even", "adverb", "surprisingly", "Even better."),
        ("back", "adverb", "to previous position", "Come back."),
        ("there", "adverb", "in that place", "Over there."),
        ("down", "adverb", "toward lower position", "Sit down."),
        ("still", "adverb", "continuing", "Still here."),
        ("much", "adverb", "greatly", "Thank you so much."),
        ("when", "adverb", "at what time", "When did you arrive?"),
    ],
    "A2": [
        ("accept", "verb", "to agree to receive", "I accept your offer."),
        ("achieve", "verb", "to accomplish", "Achieve your goals."),
        ("add", "verb", "to put together", "Add more sugar."),
        ("admit", "verb", "to confess", "He admitted his mistake."),
        ("affect", "verb", "to influence", "Weather affects mood."),
        ("afford", "verb", "to have enough money", "I can't afford it."),
        ("agree", "verb", "to have same opinion", "I agree with you."),
        ("allow", "verb", "to permit", "Allow me to help."),
        ("answer", "verb", "to respond", "Answer the question."),
        ("appear", "verb", "to become visible", "Stars appear at night."),
        ("apply", "verb", "to request formally", "Apply for a job."),
        ("arrive", "verb", "to reach destination", "We arrived safely."),
        ("avoid", "verb", "to keep away from", "Avoid the traffic."),
        ("base", "verb", "to use as foundation", "Based on facts."),
        ("beat", "verb", "to defeat", "Beat the competition."),
        ("belong", "verb", "to be property of", "This belongs to me."),
        ("break", "verb", "to damage", "Don't break it."),
        ("bring", "verb", "to carry toward", "Bring your book."),
        ("build", "verb", "to construct", "Build a house."),
        ("buy", "verb", "to purchase", "Buy groceries."),
        ("carry", "verb", "to transport", "Carry the bag."),
        ("catch", "verb", "to grab moving thing", "Catch the ball."),
        ("cause", "verb", "to make happen", "Cause problems."),
        ("change", "verb", "to make different", "Change your mind."),
        ("check", "verb", "to examine", "Check your email."),
        ("choose", "verb", "to select", "Choose wisely."),
        ("claim", "verb", "to state as fact", "He claims innocence."),
        ("clean", "verb", "to remove dirt", "Clean the room."),
        ("clear", "verb", "to make empty", "Clear the table."),
        ("close", "verb", "to shut", "Close the door."),
        ("collect", "verb", "to gather", "Collect stamps."),
        ("compare", "verb", "to examine similarities", "Compare prices."),
        ("complete", "verb", "to finish", "Complete the task."),
        ("consider", "verb", "to think about", "Consider the options."),
        ("contain", "verb", "to hold inside", "The box contains toys."),
        ("continue", "verb", "to keep going", "Continue reading."),
        ("control", "verb", "to have power over", "Control your emotions."),
        ("cook", "verb", "to prepare food", "Cook dinner."),
        ("copy", "verb", "to duplicate", "Copy the file."),
        ("cost", "verb", "to have a price", "How much does it cost?"),
        ("count", "verb", "to calculate number", "Count to ten."),
        ("cover", "verb", "to put over", "Cover with a blanket."),
        ("create", "verb", "to make something new", "Create art."),
        ("cross", "verb", "to go across", "Cross the street."),
        ("cut", "verb", "to divide with blade", "Cut the paper."),
        ("dance", "verb", "to move to music", "Dance all night."),
        ("deal", "verb", "to handle", "Deal with problems."),
        ("decide", "verb", "to make choice", "Decide quickly."),
        ("deliver", "verb", "to bring to destination", "Deliver packages."),
        ("depend", "verb", "to rely on", "It depends on you."),
        ("describe", "verb", "to tell about", "Describe yourself."),
        ("design", "verb", "to plan appearance", "Design a logo."),
        ("destroy", "verb", "to ruin completely", "Fire destroyed the building."),
        ("develop", "verb", "to grow or create", "Develop skills."),
        ("die", "verb", "to stop living", "Plants die without water."),
        ("disappear", "verb", "to vanish", "The sun disappeared."),
        ("discover", "verb", "to find for first time", "Discover new places."),
        ("discuss", "verb", "to talk about", "Discuss the topic."),
        ("draw", "verb", "to create picture", "Draw a circle."),
        ("dream", "verb", "to imagine while sleeping", "I dream of success."),
        # A2 명사
        ("ability", "noun", "skill or talent", "The ability to learn."),
        ("account", "noun", "bank record", "Open an account."),
        ("action", "noun", "activity or deed", "Take action now."),
        ("activity", "noun", "something done", "Outdoor activity."),
        ("address", "noun", "location information", "Your home address."),
        ("adult", "noun", "grown person", "Adults only."),
        ("advice", "noun", "recommendation", "Good advice."),
        ("age", "noun", "years lived", "What's your age?"),
        ("agreement", "noun", "arrangement", "Sign an agreement."),
        ("air", "noun", "atmosphere", "Fresh air."),
        ("animal", "noun", "living creature", "Wild animals."),
        ("apartment", "noun", "flat", "Rent an apartment."),
        ("appearance", "noun", "how something looks", "Nice appearance."),
        ("apple", "noun", "fruit", "Eat an apple."),
        ("application", "noun", "formal request", "Job application."),
        ("appointment", "noun", "scheduled meeting", "Doctor's appointment."),
        ("argument", "noun", "disagreement", "Avoid arguments."),
        ("arm", "noun", "body limb", "Raise your arm."),
        ("army", "noun", "military force", "Join the army."),
        ("art", "noun", "creative work", "Modern art."),
        ("article", "noun", "piece of writing", "Read an article."),
        ("artist", "noun", "creative person", "Famous artist."),
        ("attention", "noun", "focus", "Pay attention."),
        ("audience", "noun", "viewers/listeners", "Large audience."),
        ("baby", "noun", "infant", "Cute baby."),
        ("bag", "noun", "container", "Shopping bag."),
        ("ball", "noun", "round object", "Kick the ball."),
        ("bank", "noun", "financial institution", "Go to the bank."),
        ("bar", "noun", "drinking establishment", "Meet at the bar."),
        ("bath", "noun", "washing", "Take a bath."),
        ("beach", "noun", "sandy shore", "Beautiful beach."),
        ("bed", "noun", "sleeping furniture", "Go to bed."),
        ("beer", "noun", "alcoholic drink", "Cold beer."),
        ("bill", "noun", "payment request", "Pay the bill."),
        ("bird", "noun", "flying animal", "A singing bird."),
        ("birthday", "noun", "birth anniversary", "Happy birthday!"),
        ("bit", "noun", "small piece", "A bit of luck."),
        ("blood", "noun", "red body fluid", "Blood test."),
        ("board", "noun", "flat surface", "White board."),
        ("boat", "noun", "water vehicle", "Sail a boat."),
        ("body", "noun", "physical form", "Healthy body."),
        ("bone", "noun", "skeleton part", "Broken bone."),
        ("border", "noun", "boundary", "Cross the border."),
        ("boss", "noun", "supervisor", "My boss."),
        ("bottle", "noun", "container", "Water bottle."),
        ("bottom", "noun", "lowest part", "At the bottom."),
        ("box", "noun", "container", "Cardboard box."),
        ("boy", "noun", "male child", "Little boy."),
        ("brain", "noun", "thinking organ", "Use your brain."),
        ("bread", "noun", "baked food", "Fresh bread."),
        ("breakfast", "noun", "morning meal", "Eat breakfast."),
        ("breath", "noun", "inhaled air", "Take a breath."),
        ("bridge", "noun", "crossing structure", "Cross the bridge."),
        ("brother", "noun", "male sibling", "Older brother."),
        ("budget", "noun", "financial plan", "Monthly budget."),
        ("building", "noun", "structure", "Tall building."),
        ("bus", "noun", "public transport", "Take the bus."),
        ("button", "noun", "fastener or control", "Push the button."),
        # A2 형용사/부사
        ("above", "preposition", "higher than", "Above the clouds."),
        ("absent", "adjective", "not present", "Absent from school."),
        ("afraid", "adjective", "feeling fear", "Don't be afraid."),
        ("alone", "adjective", "without others", "Home alone."),
        ("angry", "adjective", "feeling anger", "Don't be angry."),
        ("available", "adjective", "able to be used", "Available now."),
        ("basic", "adjective", "fundamental", "Basic skills."),
        ("beautiful", "adjective", "very attractive", "Beautiful sunset."),
        ("below", "preposition", "lower than", "Below average."),
        ("boring", "adjective", "not interesting", "Boring movie."),
        ("bright", "adjective", "full of light", "Bright future."),
        ("busy", "adjective", "having much to do", "Very busy."),
        ("calm", "adjective", "peaceful", "Stay calm."),
        ("careful", "adjective", "cautious", "Be careful!"),
        ("cheap", "adjective", "low cost", "Cheap price."),
        ("clean", "adjective", "not dirty", "Clean water."),
        ("clever", "adjective", "smart", "Clever idea."),
        ("comfortable", "adjective", "at ease", "Comfortable chair."),
        ("common", "adjective", "widespread", "Common problem."),
        ("confident", "adjective", "self-assured", "Feel confident."),
        ("crazy", "adjective", "insane or extreme", "Crazy idea."),
        ("cultural", "adjective", "relating to culture", "Cultural event."),
        ("dangerous", "adjective", "risky", "Dangerous road."),
        ("dark", "adjective", "without light", "Dark night."),
        ("dead", "adjective", "not alive", "Dead battery."),
        ("deep", "adjective", "extending far down", "Deep water."),
        ("difficult", "adjective", "hard", "Difficult exam."),
        ("direct", "adjective", "straight", "Direct flight."),
        ("dirty", "adjective", "not clean", "Dirty clothes."),
        ("dry", "adjective", "not wet", "Dry weather."),
        ("easy", "adjective", "not difficult", "Easy question."),
        ("economic", "adjective", "relating to economy", "Economic growth."),
        ("educational", "adjective", "relating to education", "Educational video."),
        ("effective", "adjective", "producing results", "Effective method."),
        ("empty", "adjective", "containing nothing", "Empty box."),
        ("entire", "adjective", "whole", "Entire day."),
        ("environmental", "adjective", "relating to environment", "Environmental issues."),
        ("equal", "adjective", "the same", "Equal rights."),
        ("essential", "adjective", "necessary", "Essential items."),
        ("excellent", "adjective", "outstanding", "Excellent work!"),
        ("exciting", "adjective", "thrilling", "Exciting news."),
        ("expensive", "adjective", "high cost", "Expensive car."),
        ("extra", "adjective", "additional", "Extra time."),
        ("fair", "adjective", "just or reasonable", "Fair decision."),
        ("familiar", "adjective", "well known", "Familiar face."),
        ("famous", "adjective", "well known", "Famous actor."),
        ("far", "adjective", "distant", "Far away."),
        ("fast", "adjective", "quick", "Fast car."),
        ("fat", "adjective", "overweight", "Fat cat."),
        ("favorite", "adjective", "most liked", "Favorite food."),
        ("final", "adjective", "last", "Final exam."),
        ("financial", "adjective", "relating to money", "Financial support."),
        ("fine", "adjective", "acceptable", "I'm fine."),
        ("flat", "adjective", "level", "Flat surface."),
        ("foreign", "adjective", "from another country", "Foreign language."),
        ("formal", "adjective", "official", "Formal dress."),
        ("former", "adjective", "previous", "Former president."),
        ("free", "adjective", "without cost", "Free sample."),
        ("fresh", "adjective", "newly made", "Fresh bread."),
        ("friendly", "adjective", "kind", "Friendly people."),
        ("front", "adjective", "forward part", "Front door."),
        ("full", "adjective", "completely filled", "Full stomach."),
        ("funny", "adjective", "amusing", "Funny joke."),
        ("future", "adjective", "time to come", "Future plans."),
        ("general", "adjective", "overall", "General idea."),
        ("glad", "adjective", "pleased", "Glad to meet you."),
        ("global", "adjective", "worldwide", "Global warming."),
        ("green", "adjective", "color of grass", "Green light."),
        ("happy", "adjective", "feeling joy", "Happy birthday!"),
        ("hard", "adjective", "difficult or solid", "Hard work."),
        ("healthy", "adjective", "in good health", "Healthy lifestyle."),
        ("heavy", "adjective", "of great weight", "Heavy box."),
        ("helpful", "adjective", "giving help", "Helpful advice."),
        ("historical", "adjective", "relating to history", "Historical event."),
        ("honest", "adjective", "truthful", "Honest answer."),
        ("hot", "adjective", "high temperature", "Hot weather."),
        ("huge", "adjective", "very large", "Huge success."),
        ("human", "adjective", "relating to people", "Human nature."),
        ("hungry", "adjective", "wanting food", "Very hungry."),
        ("illegal", "adjective", "against law", "Illegal activity."),
        ("immediate", "adjective", "instant", "Immediate response."),
        ("impossible", "adjective", "cannot happen", "Impossible task."),
    ],
    "B1": [
        ("abandon", "verb", "to leave completely", "They abandoned the project."),
        ("absorb", "verb", "to take in", "Sponges absorb water."),
        ("abuse", "verb", "to misuse or mistreat", "Don't abuse your power."),
        ("accomplish", "verb", "to complete successfully", "She accomplished her mission."),
        ("accurate", "adjective", "exact and correct", "Accurate information is important."),
        ("accuse", "verb", "to blame someone", "They accused him of lying."),
        ("acquire", "verb", "to obtain", "Acquire new skills."),
        ("adapt", "verb", "to adjust to new conditions", "Animals adapt to their environment."),
        ("adequate", "adjective", "sufficient", "Adequate preparation is key."),
        ("adjust", "verb", "to alter slightly", "Adjust the settings."),
        ("administration", "noun", "management", "Business administration."),
        ("admire", "verb", "to respect", "I admire your courage."),
        ("adopt", "verb", "to take as one's own", "Adopt a child."),
        ("advance", "verb", "to move forward", "Technology advances rapidly."),
        ("advanced", "adjective", "highly developed", "Advanced technology."),
        ("advantage", "noun", "benefit", "Competitive advantage."),
        ("adventure", "noun", "exciting experience", "Life is an adventure."),
        ("advertise", "verb", "to promote publicly", "Advertise your product."),
        ("affair", "noun", "event or matter", "Current affairs."),
        ("afford", "verb", "to have enough money for", "Can you afford it?"),
        ("agency", "noun", "organization", "Travel agency."),
        ("agent", "noun", "representative", "Real estate agent."),
        ("aggressive", "adjective", "hostile", "Aggressive behavior."),
        ("aid", "noun", "help or assistance", "First aid."),
        ("aim", "verb", "to intend", "Aim for success."),
        ("aircraft", "noun", "flying vehicle", "Military aircraft."),
        ("alarm", "noun", "warning signal", "Fire alarm."),
        ("alcohol", "noun", "intoxicating drink", "Alcohol consumption."),
        ("alive", "adjective", "living", "Stay alive."),
        ("alliance", "noun", "union", "Political alliance."),
        ("ally", "noun", "partner", "Close ally."),
        ("alternative", "noun", "other option", "No alternative."),
        ("amazing", "adjective", "wonderful", "Amazing view!"),
        ("ambition", "noun", "strong desire to succeed", "Full of ambition."),
        ("amendment", "noun", "change to document", "Constitutional amendment."),
        ("analysis", "noun", "detailed examination", "Data analysis."),
        ("analyst", "noun", "person who analyzes", "Financial analyst."),
        ("analyze", "verb", "to examine closely", "Analyze the data."),
        ("ancestor", "noun", "forefather", "My ancestors came from Korea."),
        ("ancient", "adjective", "very old", "Ancient history."),
        ("angle", "noun", "corner or perspective", "Different angle."),
        ("anniversary", "noun", "yearly celebration", "Wedding anniversary."),
        ("announce", "verb", "to make known publicly", "Announce the winner."),
        ("annual", "adjective", "yearly", "Annual report."),
        ("anxiety", "noun", "worry", "Anxiety disorder."),
        ("anxious", "adjective", "worried", "Feeling anxious."),
        ("anyway", "adverb", "regardless", "I'll go anyway."),
        ("apart", "adverb", "separated", "Fall apart."),
        ("apologize", "verb", "to say sorry", "I apologize for the delay."),
        ("appeal", "verb", "to attract or request", "Appeal to emotions."),
        ("applaud", "verb", "to clap hands", "The audience applauded."),
        ("application", "noun", "formal request", "Job application."),
        ("appoint", "verb", "to assign to position", "Appoint a manager."),
        ("appreciate", "verb", "to value", "I appreciate your help."),
        ("approach", "noun", "method", "New approach."),
        ("appropriate", "adjective", "suitable", "Appropriate behavior."),
        ("approval", "noun", "permission", "Get approval first."),
        ("approve", "verb", "to accept officially", "Approve the plan."),
        ("approximately", "adverb", "about", "Approximately 100 people."),
        ("architect", "noun", "building designer", "Famous architect."),
        ("argue", "verb", "to disagree verbally", "Don't argue with me."),
        ("arise", "verb", "to occur", "Problems arise."),
        ("arrange", "verb", "to organize", "Arrange a meeting."),
        ("arrest", "verb", "to take into custody", "Police arrested him."),
        ("arrival", "noun", "act of arriving", "Expected arrival time."),
        ("aspect", "noun", "feature", "Important aspect."),
        ("assess", "verb", "to evaluate", "Assess the situation."),
        ("asset", "noun", "valuable item", "Company assets."),
        ("assign", "verb", "to give task", "Assign homework."),
        ("assist", "verb", "to help", "Assist customers."),
        ("associate", "verb", "to connect", "Associate with success."),
        ("association", "noun", "organization", "Business association."),
        ("assume", "verb", "to suppose", "Don't assume anything."),
        ("assumption", "noun", "supposition", "Wrong assumption."),
        ("assure", "verb", "to promise", "I assure you it's safe."),
        ("atmosphere", "noun", "air or mood", "Friendly atmosphere."),
        ("attach", "verb", "to fasten", "Attach the file."),
        ("attack", "noun", "assault", "Cyber attack."),
        ("attempt", "noun", "effort", "First attempt."),
        ("attitude", "noun", "way of thinking", "Positive attitude."),
        ("attract", "verb", "to draw toward", "Attract attention."),
        ("authority", "noun", "power to control", "Local authority."),
        ("automatic", "adjective", "self-operating", "Automatic door."),
        ("average", "adjective", "typical", "Average score."),
        ("award", "noun", "prize", "Award ceremony."),
        ("aware", "adjective", "conscious of", "Be aware of risks."),
        ("background", "noun", "past experience", "Educational background."),
        ("backward", "adverb", "toward the rear", "Step backward."),
        ("balance", "noun", "stability", "Work-life balance."),
        ("band", "noun", "music group", "Rock band."),
        ("barrier", "noun", "obstacle", "Language barrier."),
        ("basement", "noun", "underground floor", "Store in the basement."),
        ("basis", "noun", "foundation", "On a daily basis."),
        ("battery", "noun", "power source", "Phone battery."),
        ("battle", "noun", "fight", "Battle for survival."),
        ("behave", "verb", "to act", "Behave yourself!"),
        ("behavior", "noun", "conduct", "Strange behavior."),
        ("belief", "noun", "conviction", "Strong belief."),
        ("beloved", "adjective", "dearly loved", "My beloved family."),
        ("bend", "verb", "to curve", "Bend your knees."),
        ("beneath", "preposition", "under", "Beneath the surface."),
    ],
    "B2": [
        ("abolish", "verb", "to officially end", "Abolish slavery."),
        ("absence", "noun", "state of being away", "In the absence of evidence."),
        ("abstract", "adjective", "theoretical", "Abstract concept."),
        ("absurd", "adjective", "ridiculous", "Absurd idea."),
        ("abundance", "noun", "large quantity", "Abundance of resources."),
        ("academic", "adjective", "relating to education", "Academic achievement."),
        ("accelerate", "verb", "to speed up", "Accelerate growth."),
        ("accessible", "adjective", "easy to reach", "Accessible to everyone."),
        ("accommodate", "verb", "to provide for", "Accommodate guests."),
        ("accompany", "verb", "to go with", "Accompany me please."),
        ("accumulate", "verb", "to gather over time", "Accumulate wealth."),
        ("accuracy", "noun", "correctness", "Check for accuracy."),
        ("acknowledge", "verb", "to recognize", "Acknowledge mistakes."),
        ("acquisition", "noun", "obtaining", "Language acquisition."),
        ("activate", "verb", "to make active", "Activate your account."),
        ("acute", "adjective", "severe or sharp", "Acute pain."),
        ("adaptation", "noun", "adjustment", "Climate adaptation."),
        ("addiction", "noun", "dependency", "Drug addiction."),
        ("additional", "adjective", "extra", "Additional information."),
        ("adequate", "adjective", "sufficient", "Adequate supply."),
        ("adhere", "verb", "to stick to", "Adhere to rules."),
        ("adjacent", "adjective", "next to", "Adjacent rooms."),
        ("administrative", "adjective", "relating to management", "Administrative tasks."),
        ("adolescent", "noun", "teenager", "Adolescent behavior."),
        ("advocate", "verb", "to support publicly", "Advocate for change."),
        ("aesthetic", "adjective", "relating to beauty", "Aesthetic design."),
        ("affection", "noun", "fondness", "Show affection."),
        ("affiliate", "noun", "associated member", "Business affiliate."),
        ("affirm", "verb", "to state positively", "Affirm your commitment."),
        ("agenda", "noun", "list of items", "Meeting agenda."),
        ("aggregate", "adjective", "combined", "Aggregate data."),
        ("align", "verb", "to arrange in line", "Align your goals."),
        ("allegation", "noun", "accusation", "Serious allegations."),
        ("allocate", "verb", "to distribute", "Allocate resources."),
        ("alter", "verb", "to change", "Alter the design."),
        ("altitude", "noun", "height", "High altitude."),
        ("amateur", "noun", "non-professional", "Amateur photographer."),
        ("ambassador", "noun", "diplomatic representative", "US Ambassador."),
        ("ambiguous", "adjective", "unclear", "Ambiguous statement."),
        ("amid", "preposition", "in the middle of", "Amid controversy."),
        ("ammunition", "noun", "bullets", "Out of ammunition."),
        ("analogy", "noun", "comparison", "Good analogy."),
        ("anticipate", "verb", "to expect", "Anticipate problems."),
        ("apology", "noun", "expression of regret", "Accept my apology."),
        ("apparatus", "noun", "equipment", "Scientific apparatus."),
        ("apparent", "adjective", "obvious", "Apparent reason."),
        ("appetite", "noun", "desire for food", "Lost my appetite."),
        ("appliance", "noun", "household device", "Kitchen appliance."),
        ("applicable", "adjective", "relevant", "Not applicable."),
        ("arbitrary", "adjective", "random", "Arbitrary decision."),
        ("archive", "noun", "historical records", "Digital archive."),
        ("arena", "noun", "sports venue", "Concert arena."),
        ("articulate", "verb", "to express clearly", "Articulate your ideas."),
        ("artificial", "adjective", "man-made", "Artificial intelligence."),
        ("aspire", "verb", "to aim for", "Aspire to greatness."),
        ("assault", "noun", "physical attack", "Assault charges."),
        ("assemble", "verb", "to gather together", "Assemble the team."),
        ("assert", "verb", "to state firmly", "Assert your rights."),
        ("assignment", "noun", "task given", "Complete the assignment."),
        ("assimilate", "verb", "to absorb", "Assimilate information."),
        ("assumption", "noun", "thing accepted as true", "Basic assumption."),
        ("attribute", "noun", "quality", "Key attribute."),
        ("audit", "noun", "official examination", "Financial audit."),
        ("authentic", "adjective", "genuine", "Authentic experience."),
        ("authorize", "verb", "to give permission", "Authorize payment."),
        ("autonomy", "noun", "independence", "Personal autonomy."),
        ("avert", "verb", "to prevent", "Avert disaster."),
        ("ballot", "noun", "voting paper", "Cast your ballot."),
        ("bankrupt", "adjective", "financially ruined", "Go bankrupt."),
        ("bargain", "noun", "good deal", "Great bargain."),
        ("benchmark", "noun", "standard", "Industry benchmark."),
        ("beneficial", "adjective", "helpful", "Beneficial effects."),
        ("betray", "verb", "to be disloyal", "Betray trust."),
        ("bias", "noun", "prejudice", "Confirmation bias."),
        ("blend", "verb", "to mix", "Blend ingredients."),
        ("boost", "verb", "to increase", "Boost confidence."),
        ("boundary", "noun", "limit", "Set boundaries."),
        ("breach", "noun", "violation", "Security breach."),
        ("breakthrough", "noun", "important discovery", "Scientific breakthrough."),
        ("brutal", "adjective", "cruel", "Brutal attack."),
        ("bureaucracy", "noun", "administrative system", "Government bureaucracy."),
        ("campaign", "noun", "organized effort", "Marketing campaign."),
        ("capability", "noun", "ability", "Technical capability."),
        ("capitalism", "noun", "economic system", "Free market capitalism."),
        ("capture", "verb", "to catch", "Capture the moment."),
        ("carbon", "noun", "chemical element", "Carbon footprint."),
        ("catalog", "noun", "list of items", "Product catalog."),
        ("catastrophe", "noun", "disaster", "Natural catastrophe."),
        ("cease", "verb", "to stop", "Cease fire."),
        ("celebrity", "noun", "famous person", "Celebrity status."),
        ("certify", "verb", "to officially confirm", "Certify documents."),
        ("chaos", "noun", "complete disorder", "Total chaos."),
        ("characterize", "verb", "to describe", "Characterize the problem."),
        ("chronic", "adjective", "long-lasting", "Chronic disease."),
        ("circulate", "verb", "to move around", "Circulate information."),
        ("cite", "verb", "to quote", "Cite your sources."),
        ("civilization", "noun", "advanced society", "Ancient civilization."),
        ("clarity", "noun", "clearness", "Need more clarity."),
        ("classify", "verb", "to categorize", "Classify data."),
        ("clause", "noun", "section of document", "Contract clause."),
    ],
    "C1": [
        ("abide", "verb", "to accept or follow", "Abide by the rules."),
        ("abolition", "noun", "act of ending", "Abolition of death penalty."),
        ("abrupt", "adjective", "sudden", "Abrupt change."),
        ("abstain", "verb", "to refrain from", "Abstain from voting."),
        ("abstraction", "noun", "concept", "Mathematical abstraction."),
        ("absurdity", "noun", "ridiculousness", "The absurdity of the situation."),
        ("acclaimed", "adjective", "highly praised", "Critically acclaimed."),
        ("accomplishment", "noun", "achievement", "Great accomplishment."),
        ("accountability", "noun", "responsibility", "Corporate accountability."),
        ("accreditation", "noun", "official recognition", "University accreditation."),
        ("accumulation", "noun", "gradual gathering", "Wealth accumulation."),
        ("acquaintance", "noun", "person known slightly", "Just an acquaintance."),
        ("adamant", "adjective", "refusing to change", "Adamant about his decision."),
        ("adjacent", "adjective", "next to", "Adjacent building."),
        ("adjunct", "noun", "addition", "Adjunct professor."),
        ("administer", "verb", "to manage", "Administer the test."),
        ("admirable", "adjective", "worthy of admiration", "Admirable qualities."),
        ("advent", "noun", "arrival", "The advent of technology."),
        ("adversary", "noun", "opponent", "Political adversary."),
        ("adverse", "adjective", "unfavorable", "Adverse effects."),
        ("adversity", "noun", "hardship", "Overcome adversity."),
        ("advocacy", "noun", "public support", "Environmental advocacy."),
        ("affluent", "adjective", "wealthy", "Affluent neighborhood."),
        ("aftermath", "noun", "consequences", "In the aftermath."),
        ("aggravate", "verb", "to make worse", "Aggravate the situation."),
        ("aggregate", "verb", "to combine", "Aggregate the results."),
        ("agitation", "noun", "anxiety or unrest", "Political agitation."),
        ("albeit", "conjunction", "although", "Albeit slowly."),
        ("algorithm", "noun", "procedure", "Search algorithm."),
        ("alienate", "verb", "to isolate", "Alienate friends."),
        ("alleviate", "verb", "to reduce", "Alleviate pain."),
        ("allot", "verb", "to distribute", "Allot time wisely."),
        ("allusion", "noun", "indirect reference", "Literary allusion."),
        ("alteration", "noun", "change", "Minor alteration."),
        ("ambivalent", "adjective", "having mixed feelings", "Ambivalent about the decision."),
        ("amend", "verb", "to change formally", "Amend the constitution."),
        ("amenity", "noun", "useful feature", "Hotel amenities."),
        ("amplify", "verb", "to increase", "Amplify the sound."),
        ("analogue", "noun", "comparable thing", "Digital versus analogue."),
        ("anarchist", "noun", "opponent of government", "Political anarchist."),
        ("anatomy", "noun", "body structure", "Human anatomy."),
        ("anecdote", "noun", "short story", "Personal anecdote."),
        ("anguish", "noun", "severe distress", "Mental anguish."),
        ("animate", "verb", "to bring to life", "Animate characters."),
        ("annex", "verb", "to add territory", "Annex territory."),
        ("anomaly", "noun", "irregularity", "Statistical anomaly."),
        ("anonymous", "adjective", "unnamed", "Anonymous donor."),
        ("antagonist", "noun", "opponent", "The story's antagonist."),
        ("anthology", "noun", "collection of works", "Poetry anthology."),
        ("anthropology", "noun", "study of humans", "Cultural anthropology."),
        ("apartheid", "noun", "racial segregation", "South African apartheid."),
        ("apathy", "noun", "lack of interest", "Voter apathy."),
        ("apex", "noun", "highest point", "At the apex."),
        ("appalling", "adjective", "shocking", "Appalling conditions."),
        ("apparition", "noun", "ghost", "Strange apparition."),
        ("apprehend", "verb", "to arrest or understand", "Apprehend the suspect."),
        ("apprehension", "noun", "anxiety or arrest", "Growing apprehension."),
        ("apprentice", "noun", "trainee", "Apprentice electrician."),
        ("aptitude", "noun", "natural ability", "Aptitude test."),
        ("arbitrary", "adjective", "random", "Arbitrary decision."),
        ("arc", "noun", "curved line", "Story arc."),
        ("archaic", "adjective", "outdated", "Archaic language."),
        ("archipelago", "noun", "island group", "Philippine archipelago."),
        ("ardent", "adjective", "passionate", "Ardent supporter."),
        ("arduous", "adjective", "difficult", "Arduous journey."),
        ("aristocracy", "noun", "ruling class", "British aristocracy."),
        ("armament", "noun", "weapons", "Nuclear armament."),
        ("articulation", "noun", "expression", "Clear articulation."),
        ("artifact", "noun", "historical object", "Ancient artifact."),
        ("ascend", "verb", "to go up", "Ascend the mountain."),
        ("ascertain", "verb", "to find out", "Ascertain the facts."),
        ("aspiration", "noun", "ambition", "Career aspirations."),
        ("assassination", "noun", "political murder", "Assassination attempt."),
        ("assemblage", "noun", "collection", "Art assemblage."),
        ("assertion", "noun", "confident statement", "Bold assertion."),
        ("assortment", "noun", "variety", "Assortment of chocolates."),
        ("asylum", "noun", "protection", "Political asylum."),
        ("atrocity", "noun", "cruel act", "War atrocities."),
        ("attain", "verb", "to achieve", "Attain success."),
        ("attest", "verb", "to provide evidence", "Attest to the quality."),
        ("audacity", "noun", "boldness", "The audacity!"),
        ("augment", "verb", "to increase", "Augment reality."),
        ("aura", "noun", "atmosphere", "Mysterious aura."),
        ("austerity", "noun", "severity", "Austerity measures."),
        ("authenticate", "verb", "to verify", "Authenticate identity."),
        ("authoritarian", "adjective", "dictatorial", "Authoritarian regime."),
        ("autobiography", "noun", "self-written life story", "Published autobiography."),
        ("autonomy", "noun", "self-governance", "Regional autonomy."),
        ("autopsy", "noun", "examination of dead body", "Autopsy report."),
        ("aversion", "noun", "strong dislike", "Aversion to risk."),
        ("avid", "adjective", "enthusiastic", "Avid reader."),
        ("axiom", "noun", "accepted truth", "Mathematical axiom."),
        ("backdrop", "noun", "background", "Political backdrop."),
        ("backlash", "noun", "adverse reaction", "Public backlash."),
        ("bailout", "noun", "financial rescue", "Bank bailout."),
        ("bandwidth", "noun", "data capacity", "Limited bandwidth."),
        ("barter", "verb", "to trade", "Barter goods."),
        ("bastion", "noun", "stronghold", "Last bastion."),
        ("befriend", "verb", "to become friends with", "Befriend strangers."),
        ("beleaguered", "adjective", "troubled", "Beleaguered company."),
        ("benevolent", "adjective", "kind", "Benevolent dictator."),
    ],
}


def generate_words_data() -> list[dict]:
    """단어 데이터 생성"""
    words = []
    word_id = 1
    
    for level, word_list in CORE_WORDS.items():
        for word_tuple in word_list:
            word, pos, definition, example = word_tuple
            words.append({
                "id": word_id,
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "definitionKr": "",  # 나중에 번역
                "example": example,
                "exampleKr": ""  # 나중에 번역
            })
            word_id += 1
    
    return words


async def translate_batch(texts: list[str], session: aiohttp.ClientSession) -> list[str]:
    """배치로 번역 (한번에 여러 문장)"""
    results = []
    
    for text in texts:
        try:
            params = {"q": text[:500], "langpair": "en|ko"}
            async with session.get(
                "https://api.mymemory.translated.net/get",
                params=params,
                timeout=aiohttp.ClientTimeout(total=5)
            ) as response:
                if response.status == 200:
                    data = await response.json()
                    translated = data.get("responseData", {}).get("translatedText", text)
                    results.append(translated)
                else:
                    results.append(text)
        except Exception:
            results.append(text)
        
        await asyncio.sleep(0.1)  # Rate limit
    
    return results


async def translate_all_words(words: list[dict]) -> list[dict]:
    """모든 단어 번역"""
    print(f"🌐 {len(words)}개 단어 번역 중...")
    
    connector = aiohttp.TCPConnector(limit=10)
    async with aiohttp.ClientSession(connector=connector) as session:
        # 정의 번역
        definitions = [w["definition"] for w in words]
        examples = [w["example"] for w in words]
        
        # 배치로 나눠서 번역
        batch_size = 50
        translated_defs = []
        translated_exs = []
        
        for i in range(0, len(definitions), batch_size):
            batch_defs = definitions[i:i+batch_size]
            batch_exs = examples[i:i+batch_size]
            
            print(f"  번역 중: {i+1}-{min(i+batch_size, len(definitions))}/{len(definitions)}")
            
            trans_defs = await translate_batch(batch_defs, session)
            trans_exs = await translate_batch(batch_exs, session)
            
            translated_defs.extend(trans_defs)
            translated_exs.extend(trans_exs)
        
        # 결과 적용
        for i, word in enumerate(words):
            word["definitionKr"] = translated_defs[i] if i < len(translated_defs) else word["definition"]
            word["exampleKr"] = translated_exs[i] if i < len(translated_exs) else word["example"]
    
    return words


def save_words(filepath: Path, words: list):
    """저장"""
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)


async def main():
    print("=" * 60)
    print("📚 영어 단어장 - 핵심 단어 데이터 생성")
    print("=" * 60)
    
    # 경로
    script_dir = Path(__file__).parent
    words_file = script_dir.parent / "assets" / "data" / "words.json"
    
    # 데이터 생성
    print("\n📝 단어 데이터 생성 중...")
    words = generate_words_data()
    print(f"   생성된 단어: {len(words)}개")
    
    # 레벨별 통계
    level_counts = {}
    for w in words:
        level_counts[w["level"]] = level_counts.get(w["level"], 0) + 1
    print("\n📊 레벨별 분포:")
    for level in ["A1", "A2", "B1", "B2", "C1"]:
        print(f"   {level}: {level_counts.get(level, 0)}개")
    
    # 번역 여부 확인
    translate = input("\n🌐 한국어 번역을 추가할까요? (y/n, 기본: y): ").strip().lower()
    if translate != 'n':
        start = time.time()
        words = await translate_all_words(words)
        print(f"   번역 완료: {time.time() - start:.1f}초")
    
    # 저장
    save_words(words_file, words)
    print(f"\n✅ 저장 완료: {words_file}")
    print(f"   총 단어 수: {len(words)}개")


if __name__ == "__main__":
    asyncio.run(main())
